project:
  type: website

website:
  title: "hello_qgis"
  navbar:
    left:
      - href: intro.html
        text: Introduction
      - href: Methdology.html
        text: Methdology
      - href: analysis.html
        text: Analysis
      - href: finding.html
        text: Results & Discussion
        
    right: 
      - href: index.html
        text: Home
      - about.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

